/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    container: {
      center: true,
      padding: '1rem',
    },
    extend: {
      colors: {
        // Enhanced AgriCredit Design System Colors
        'agri-green': {
          DEFAULT: '#2E7D32',
          light: '#4CAF50',
          dark: '#1B5E20',
          50: '#E8F5E8',
          100: '#C8E6C9',
          200: '#A5D6A7',
          300: '#81C784',
          400: '#66BB6A',
          500: '#4CAF50',
          600: '#43A047',
          700: '#388E3C',
          800: '#2E7D32',
          900: '#1B5E20',
        },
        'harvest-gold': {
          DEFAULT: '#FFD700',
          light: '#FFEB3B',
          dark: '#F57F17',
          50: '#FFFDE7',
          100: '#FFF9C4',
          200: '#FFF59D',
          300: '#FFF176',
          400: '#FFEE58',
          500: '#FFEB3B',
          600: '#FDD835',
          700: '#F9A825',
          800: '#F57F17',
          900: '#EF6C00',
        },
        'earth-brown': {
          DEFAULT: '#6D4C41',
          light: '#8D6E63',
          dark: '#4E342E',
          50: '#EFEBE9',
          100: '#D7CCC8',
          200: '#BCAAA4',
          300: '#A1887F',
          400: '#8D6E63',
          500: '#795548',
          600: '#6D4C41',
          700: '#5D4037',
          800: '#4E342E',
          900: '#3E2723',
        },
        'sky-teal': {
          DEFAULT: '#00C853',
          light: '#00E676',
          dark: '#00BFA5',
          50: '#E8F5E8',
          100: '#B9F6CA',
          200: '#69F0AE',
          300: '#00E676',
          400: '#00C853',
          500: '#00BF72',
          600: '#00BFA5',
          700: '#00A085',
          800: '#00897B',
          900: '#00695C',
        },
        'paper-white': '#FDFCF9',
        'slate-gray': {
          DEFAULT: '#1E1E1E',
          light: '#424242',
          dark: '#121212',
          50: '#FAFAFA',
          100: '#F5F5F5',
          200: '#EEEEEE',
          300: '#E0E0E0',
          400: '#BDBDBD',
          500: '#9E9E9E',
          600: '#757575',
          700: '#616161',
          800: '#424242',
          900: '#212121',
        },

        // Enhanced Semantic colors
        success: {
          DEFAULT: '#00C853',
          light: '#B9F6CA',
          dark: '#00A085',
        },
        warning: {
          DEFAULT: '#FFB300',
          light: '#FFF9C4',
          dark: '#F57F17',
        },
        error: {
          DEFAULT: '#D32F2F',
          light: '#FFCDD2',
          dark: '#B71C1C',
        },
        info: {
          DEFAULT: '#1976D2',
          light: '#BBDEFB',
          dark: '#0D47A1',
        },

        // Shadcn/ui compatible colors with enhanced AgriCredit theme
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        // Typography from specs.json
        sans: ['Poppins', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        // Type scale from specs.json
        'xs': ['12px', { lineHeight: '16px' }],
        'sm': ['14px', { lineHeight: '20px' }],
        'base': ['16px', { lineHeight: '24px' }],
        'lg': ['18px', { lineHeight: '28px' }],
        'xl': ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '36px' }],
        '4xl': ['36px', { lineHeight: '40px' }],
        '5xl': ['48px', { lineHeight: '1' }],
        '6xl': ['60px', { lineHeight: '1' }],
      },
      fontWeight: {
        thin: '100',
        extralight: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
      spacing: {
        // Spacing system from specs.json (base unit: 8px)
        '0': '0',
        '1': '8px',
        '2': '16px',
        '3': '24px',
        '4': '32px',
        '5': '40px',
        '6': '48px',
        '8': '64px',
        '10': '80px',
        '12': '96px',
        '16': '128px',
        '20': '160px',
        '24': '192px',
        '32': '256px',
        // Custom spacing
        '18': '4.5rem',
        '88': '22rem',
        '112': '28rem',
        '128': '32rem',
      },
      borderRadius: {
        // Border radius from specs.json
        'none': '0',
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '24px',
        '2xl': '32px',
        '3xl': '48px',
        'full': '9999px',
        // Shadcn compatibility
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        // Shadow system from specs.json
        'none': 'none',
        'level1': '0 1px 2px rgba(0,0,0,0.05)',
        'level2': '0 4px 8px rgba(0,0,0,0.08)',
        'level3': '0 8px 24px rgba(0,0,0,0.12)',
        'level4': '0 8px 32px rgba(0,0,0,0.16)',
        'level5': '0 16px 64px rgba(0,0,0,0.24)',
      },
      animation: {
        // Animations from specs.json
        'fadeIn': 'fadeIn 0.5s ease-in-out',
        'slideUp': 'slideUp 0.3s ease-out',
        'slideDown': 'slideDown 0.3s ease-out',
        'slideLeft': 'slideLeft 0.3s ease-out',
        'slideRight': 'slideRight 0.3s ease-out',
        'scaleIn': 'scaleIn 0.2s ease-out',
        'scaleOut': 'scaleOut 0.2s ease-out',
        'bounceIn': 'bounceIn 0.6s ease-out',
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin': 'spin 1s linear infinite',
        // Micro animations
        'ai-score-pulse': 'aiScorePulse 600ms ease-in-out infinite',
        'button-press': 'buttonPress 100ms ease-out',
        // Page transitions
        'fade-slide': 'fadeIn 300ms ease-out, slideUp 300ms ease-out',
        'holo-swap': 'holoSwap 600ms ease-out',
        // Loading animations
        'data-shimmer': 'dataShimmer 1400ms ease-in-out infinite',
        'map-pulse': 'mapPulse 2000ms ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1.05)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        bounceIn: {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.9)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        aiScorePulse: {
          '0%, 100%': { transform: 'scale(0.98)' },
          '50%': { transform: 'scale(1.02)' },
        },
        buttonPress: {
          '0%': { transform: 'translateY(0)', boxShadow: 'var(--tw-shadow-level1)' },
          '50%': { transform: 'translateY(2px)', boxShadow: 'var(--tw-shadow-level2)' },
          '100%': { transform: 'translateY(0)', boxShadow: 'var(--tw-shadow-level1)' },
        },
        holoSwap: {
          '0%': { opacity: '0', transform: 'scale(0.8)', filter: 'hue-rotate(0deg) brightness(1)' },
          '25%': { opacity: '0.7', transform: 'scale(1.05)', filter: 'hue-rotate(90deg) brightness(1.2)' },
          '50%': { opacity: '1', transform: 'scale(1)', filter: 'hue-rotate(180deg) brightness(1.1)' },
          '75%': { opacity: '0.9', transform: 'scale(0.98)', filter: 'hue-rotate(270deg) brightness(1.3)' },
          '100%': { opacity: '1', transform: 'scale(1)', filter: 'hue-rotate(360deg) brightness(1)' },
        },
        dataShimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        mapPulse: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.2)', opacity: '0.7' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      screens: {
        'xs': '475px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [],
}